<?php

declare(strict_types=1);

/**
 * Add deposit: GET form (store + token), POST create deposit (address NULL; cron fills). CSRF required.
 */
require_once __DIR__ . '/../includes/web_bootstrap.php';

$pageTitle = 'Add deposit';
if (!$currentUser) {
    header('Location: /login.php?redirect=' . urlencode('/deposits/add.php'));
    exit;
}

$stmt = $pdo->prepare('SELECT s.uuid, s.storename FROM stores s JOIN store_users su ON s.uuid = su.store_uuid WHERE su.user_uuid = ? AND s.deleted_at IS NULL ORDER BY s.storename');
$stmt->execute([$currentUser['uuid']]);
$stores = $stmt->fetchAll(\PDO::FETCH_ASSOC);

$tokensStmt = $pdo->query('SELECT id, chain_id, symbol, contract_address FROM accepted_tokens ORDER BY chain_id, symbol');
$tokens = $tokensStmt->fetchAll(\PDO::FETCH_ASSOC);

$error = '';
$success = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!$session->validateCsrfToken((string) ($_POST['csrf_token'] ?? ''))) {
        $error = 'Invalid request. Please try again.';
    } elseif (empty($stores)) {
        $error = 'You have no store. Create a store first.';
    } else {
        $storeUuid = trim((string) ($_POST['store_uuid'] ?? ''));
        $tokenId = (int) ($_POST['token_id'] ?? 0);
        $currency = trim((string) ($_POST['currency'] ?? 'USD'));
        if ($currency === '') {
            $currency = 'USD';
        }
        $validStore = false;
        foreach ($stores as $s) {
            if ($s['uuid'] === $storeUuid) {
                $validStore = true;
                break;
            }
        }
        $token = null;
        foreach ($tokens as $t) {
            if ((int) $t['id'] === $tokenId) {
                $token = $t;
                break;
            }
        }
        if (!$validStore) {
            $error = 'Select a valid store.';
        } elseif (!$token) {
            $error = 'Select a valid token.';
        } else {
            $uuid = User::generateUuid();
            $now = date('Y-m-d H:i:s');
            $crypto = $token['symbol'];
            $pdo->prepare('INSERT INTO deposits (uuid, store_uuid, currency, crypto, address, crypto_value, fiat_value, currency_rate, created_at) VALUES (?, ?, ?, ?, NULL, 0, 0, 1, ?)')->execute([$uuid, $storeUuid, $currency, $crypto, $now]);
            $success = 'Deposit created. Address will be generated by the system.';
            header('Location: /deposits.php?created=1');
            exit;
        }
    }
}

$csrf = $session->getCsrfToken();
require_once __DIR__ . '/../includes/web_header.php';
?>
<h1>Add deposit</h1>
<?php if ($error): ?><p class="alert alert-warning"><?= htmlspecialchars($error) ?></p><?php endif; ?>
<?php if (empty($stores)): ?>
    <p>You have no store. <a href="/create-store.php">Create a store</a> first.</p>
<?php elseif (empty($tokens)): ?>
    <p>No accepted tokens configured. An admin must add tokens first.</p>
<?php else: ?>
<form method="post">
    <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrf) ?>">
    <p>
        <label>Store <select name="store_uuid" required>
            <?php foreach ($stores as $s): ?>
                <option value="<?= htmlspecialchars($s['uuid']) ?>"><?= htmlspecialchars($s['storename']) ?></option>
            <?php endforeach; ?>
        </select></label>
    </p>
    <p>
        <label>Token <select name="token_id" required>
            <?php foreach ($tokens as $t): ?>
                <option value="<?= (int) $t['id'] ?>"><?= htmlspecialchars($t['symbol']) ?> (chain <?= (int) $t['chain_id'] ?>)</option>
            <?php endforeach; ?>
        </select></label>
    </p>
    <p>
        <label>Currency <input type="text" name="currency" value="USD" maxlength="10"></label>
    </p>
    <p><button type="submit">Create deposit</button></p>
</form>
<?php endif; ?>
<p style="margin-top: 1rem;"><a href="/deposits.php" class="btn">← Deposits</a></p>
<?php require_once __DIR__ . '/../includes/web_footer.php';
